import { lazy } from 'react';
import type { FieldDef } from './types';

export const SECTION_COMPONENTS = {
  hero:              lazy(() => import('./sections/HeroSection')),
  cinematic_hero:    lazy(() => import('./sections/CinematicHeroSection')),
  category_bar:      lazy(() => import('./sections/CategoryBarSection')),
  campaign_carousel: lazy(() => import('./sections/CampaignCarouselSection')),
  best_sellers:      lazy(() => import('./sections/BestSellersSection')),
  collections:       lazy(() => import('./sections/CollectionsSection')),
  text_reveal:       lazy(() => import('./sections/TextRevealSection')),
  editorial_split:   lazy(() => import('./sections/EditorialSplitSection')),
  bento_grid:        lazy(() => import('./sections/BentoGridSection')),
  new_arrivals:      lazy(() => import('./sections/NewArrivalsSection')),
  category_grid:     lazy(() => import('./sections/CategoryGridSection')),
  marquee:           lazy(() => import('./sections/MarqueeSection')),
  testimonials:      lazy(() => import('./sections/TestimonialsSection')),
  lookbook:          lazy(() => import('./sections/LookbookSection')),
  newsletter:        lazy(() => import('./sections/NewsletterSection')),
  promo_banner:      lazy(() => import('./sections/PromoBannerSection')),
  faq:               lazy(() => import('./sections/FAQSection')),
  linen_collection:  lazy(() => import('./sections/LinenCollectionSection')),
  instagram_reels:   lazy(() => import('./sections/InstagramReelsSection')),
  flagship_stores:   lazy(() => import('./sections/FlagshipStoresSection')),
  community:         lazy(() => import('./sections/CommunitySection')),
  influencer_picks:  lazy(() => import('./sections/InfluencerPicksSection')),
  product_marquee:   lazy(() => import('./sections/ProductMarqueeSection')),
  photo_shuffle:     lazy(() => import('./sections/PhotoShuffleSection')),
  split_scroll:      lazy(() => import('./sections/SplitScrollSection')),
  colour_story:      lazy(() => import('./sections/ColourStorySection')),
  standing_look:     lazy(() => import('./sections/StandingLookSection')),
  phone_showcase:    lazy(() => import('./sections/PhoneShowcaseSection')),
  category_cards:    lazy(() => import('./sections/CategoryCardsSection')),
  polka_bento:       lazy(() => import('./sections/PolkaBentoSection')),
  drop_countdown:    lazy(() => import('./sections/DropCountdownSection')),
  services_strip:    lazy(() => import('./sections/ServicesStripSection')),
};

export const SECTION_META: Record<string, { label: string; description: string }> = {
  product_marquee:  { label: 'Product Belt',     description: 'Product tiles sliding endlessly across a campaign photo' },
  photo_shuffle:    { label: 'Photo Shuffle',    description: 'Black-and-white tiles swapping places beside a lookbook panel' },
  split_scroll:     { label: 'Split Scroll',     description: 'Pinned red panel with sliding giant type beside a scrolling product column' },
  category_cards:   { label: 'Category Cards',   description: 'Full-screen stacking Men / Women / Sneakers cards' },
  polka_bento:      { label: 'Season Board',     description: 'Bento mosaic of campaign imagery, live products and statement tiles' },
  drop_countdown:   { label: 'Drop Countdown',   description: 'Live countdown to the next drop with notify-me form' },
  services_strip:   { label: 'Store Promise',    description: 'Numbered shipping / returns / exchange / payment columns' },
  phone_showcase:   { label: 'Phone Showcase',   description: 'Pinned red panel: three phones running the store around a full-length model' },
  standing_look:    { label: 'Standing Look',    description: 'Tall red panel: pinned full-length model beside a long product column' },
  colour_story:     { label: 'Colour Stories',   description: 'Palette bars that slide in and link to colour searches' },
  hero:             { label: 'Hero',             description: 'Full-screen hero with background image and search' },
  cinematic_hero:   { label: 'Cinematic 3D Hero',description: 'Apple-quality smooth scroll 3D frame sequence product showcase' },
  category_bar:      { label: 'Category Bar',     description: 'Horizontal clothing category cards bar with thumbnails' },
  campaign_carousel:{ label: 'Campaign Carousel',description: 'Full-width rounded hero campaign banner slider' },
  best_sellers:      { label: 'Best Sellers',     description: 'Curated showcase of top-rated iconic pieces' },
  collections:       { label: 'New Collections',  description: 'Curated seasonal capsule collections grid' },
  text_reveal:      { label: 'Text Reveal',      description: 'Animated large-type reveal words' },
  editorial_split:  { label: 'Editorial Split',  description: 'Two-column: image on one side, text on the other' },
  bento_grid:       { label: 'Bento Grid',       description: 'Magazine-style image grid' },
  new_arrivals:     { label: 'New Arrivals',      description: 'Featured product grid from catalog' },
  category_grid:    { label: 'Category Grid',    description: 'Shop category blocks with hero images' },
  marquee:          { label: 'Marquee',          description: 'Editorial statement section with animated background' },
  testimonials:     { label: 'Testimonials',     description: 'Draggable customer review carousel' },
  lookbook:         { label: 'Lookbook',         description: 'Photo gallery grid' },
  newsletter:       { label: 'Newsletter',       description: 'Email signup / Join the Vault section' },
  promo_banner:     { label: 'Promo Banner',     description: 'Full-width promotional strip' },
  faq:              { label: 'FAQ',              description: 'Expandable frequently asked questions' },
  linen_collection: { label: 'Linen Collection', description: 'Summer European linen capsule showcase' },
  instagram_reels:  { label: 'Instagram Reels',   description: 'Interactive video reels showcase' },
  flagship_stores:  { label: 'Flagship Stores',  description: 'Daily Paper style flagship storefront showcase with giant brand text' },
  community:        { label: 'Community',        description: 'Bento-grid gallery of community/customer photos' },
  influencer_picks: { label: 'Influencer Picks', description: 'Grid of influencer/creator style picks with video or link' },
};

// ─── Field shortcuts ─────────────────────────────────────────────────────────
/** "Automatic" (the section's built-in choice) or hand-picked products via search. */
const PRODUCTS = (max?: number): FieldDef[] => [
  { key: 'product_mode', label: 'Products shown', type: 'select', options: [{ value: 'auto', label: 'Automatic' }, { value: 'manual', label: 'Pick products' }] },
  { key: 'product_slugs', label: 'Pick products', type: 'products', max, showIf: { key: 'product_mode', equals: 'manual' },
    hint: max ? `Up to ${max}. Search, click to add, arrows to reorder.` : 'Search, click to add, arrows to reorder.' },
];
const LINK = (key: string, label: string): FieldDef => ({ key, label, type: 'link', hint: 'Pick a product, a category or a page.' });
const MEDIA = (key: string, label: string, kind: FieldDef['kind'] = 'image'): FieldDef => ({ key, label, type: 'media', kind });
const TEXT = (key: string, label: string, placeholder?: string): FieldDef => ({ key, label, type: 'text', placeholder });
const AREA = (key: string, label: string, placeholder?: string): FieldDef => ({ key, label, type: 'textarea', placeholder });

export const SECTION_FIELDS: Record<string, FieldDef[]> = {
  hero: [
    { key: 'heading',           label: 'Main Heading',        type: 'text',     placeholder: 'BEYOND' },
    { key: 'heading_italic',    label: 'Italic Part',         type: 'text',     placeholder: 'TRENDS.' },
    { key: 'eyebrow',           label: 'Eyebrow Label',       type: 'text' },
    { key: 'background_image',  label: 'Background Image URL',type: 'url' },
    { key: 'search_placeholder',label: 'Search Placeholder',  type: 'text' },
    { key: 'search_cta',        label: 'Search Button Text',  type: 'text' },
    { key: 'cta_href',          label: 'Search CTA Link',     type: 'text' },
    { key: 'social_proof_count',label: 'Social Proof Count',  type: 'text',     placeholder: '2K+' },
    { key: 'social_proof_text', label: 'Social Proof Text',   type: 'text' },
  ],
  category_bar: [
    { key: 'categories', label: 'Categories (JSON)', type: 'json', hint: '[{slug, title, image, href}]' },
  ],
  best_sellers: [
    { key: 'eyebrow',      label: 'Eyebrow Label',    type: 'text' },
    { key: 'title',        label: 'Section Title',    type: 'text' },
    { key: 'subtitle',     label: 'Subtitle',         type: 'text' },
    { key: 'cta_label',    label: 'CTA Label',        type: 'text' },
    LINK('cta_link', 'CTA goes to'),
    { key: 'product_count',label: 'Products to Show (automatic mode)', type: 'number' },
    ...PRODUCTS(),
  ],
  text_reveal: [
    { key: 'words',           label: 'Words (JSON array)',  type: 'json', hint: '["ATTITUDE","CONFIDENCE"]' },
    { key: 'show_accent_line',label: 'Show Accent Line',   type: 'boolean' },
  ],
  editorial_split: [
    { key: 'image',         label: 'Image URL',              type: 'url' },
    { key: 'accent_number', label: 'Accent Number',          type: 'text',  placeholder: '26' },
    { key: 'heading_lines', label: 'Heading Lines (JSON)',   type: 'json',  hint: '["Redefining","Street Culture"]' },
    { key: 'body',          label: 'Body Text',              type: 'textarea' },
    { key: 'cta_label',     label: 'CTA Label',              type: 'text' },
    { key: 'cta_href',      label: 'CTA Link',               type: 'text' },
  ],
  bento_grid: [
    { key: 'eyebrow',       label: 'Eyebrow',                type: 'text' },
    { key: 'heading',       label: 'Heading',                type: 'text' },
    { key: 'heading_italic',label: 'Heading Italic Part',    type: 'text' },
    { key: 'cta_label',     label: 'CTA Label',              type: 'text' },
    { key: 'cta_href',      label: 'CTA Link',               type: 'text' },
    { key: 'items',         label: 'Grid Items (JSON)',       type: 'json',  hint: '[{title, category, image, href, col_span, row_span}]' },
  ],
  new_arrivals: [
    { key: 'eyebrow',      label: 'Eyebrow',          type: 'text' },
    { key: 'title',        label: 'Section Title',    type: 'text' },
    { key: 'subtitle',     label: 'Subtitle',         type: 'text' },
    { key: 'cta_label',    label: 'CTA Label',        type: 'text' },
    LINK('cta_link', 'CTA goes to'),
    { key: 'product_count',label: 'Products to Show (automatic mode)', type: 'number' },
    ...PRODUCTS(),
  ],
  category_grid: [
    { key: 'categories', label: 'Categories (JSON)', type: 'json', hint: '[{slug, title, image, href, watermark, badge?}]' },
  ],
  marquee: [
    { key: 'heading',        label: 'Heading',            type: 'text' },
    { key: 'heading_italic', label: 'Heading Italic Part',type: 'text' },
    { key: 'subtext',        label: 'Subtext',            type: 'text' },
    { key: 'watermark',      label: 'Watermark Character',type: 'text', placeholder: '26' },
  ],
  testimonials: [
    { key: 'heading',        label: 'Heading',            type: 'text' },
    { key: 'heading_italic', label: 'Heading Italic',     type: 'text' },
  ],
  lookbook: [
    { key: 'heading', label: 'Heading', type: 'text', placeholder: 'VAULT 26 JOURNAL' },
    { key: 'subtitle', label: 'Subtitle', type: 'text', placeholder: 'EDITORIAL & LOOKBOOK' },
  ],
  newsletter: [
    { key: 'heading_line1', label: 'Heading Line 1',  type: 'text' },
    { key: 'heading_line2', label: 'Heading Line 2',  type: 'text' },
    { key: 'body',          label: 'Body Text',       type: 'textarea' },
    { key: 'placeholder',   label: 'Email Placeholder',type: 'text' },
    { key: 'cta_label',     label: 'CTA Label',       type: 'text' },
  ],
  promo_banner: [
    { key: 'message',   label: 'Message',         type: 'text' },
    { key: 'cta_label', label: 'CTA Label',        type: 'text' },
    { key: 'cta_href',  label: 'CTA Link',         type: 'text' },
    { key: 'bg_color',  label: 'Background Color', type: 'color' },
    { key: 'text_color',label: 'Text Color',       type: 'color' },
  ],
  faq: [
    { key: 'heading',  label: 'Section Heading',         type: 'text' },
    { key: 'category', label: 'Category Filter (empty=all)', type: 'text' },
  ],
  community: [
    { key: 'heading', label: 'Heading', type: 'text', placeholder: 'WORN BY VAULT 26' },
    { key: 'subtitle', label: 'Subtitle', type: 'text', placeholder: 'FROM THE COMMUNITY' },
  ],
  influencer_picks: [
    { key: 'heading', label: 'Heading', type: 'text', placeholder: 'STYLED BY' },
    { key: 'subtitle', label: 'Subtitle', type: 'text', placeholder: 'INFLUENCER PICKS' },
  ],
  collections: [
    TEXT('title', 'Heading', 'NEW COLLECTION'), TEXT('subtitle', 'Subheading', 'SEASONAL ARCHIVE 01'),
    TEXT('cta_label', 'Button text', 'VIEW ALL COLLECTIONS'), LINK('cta_link', 'Button goes to'),
    ...PRODUCTS(4),
  ],
  linen_collection: [
    TEXT('title', 'Heading', 'SPRING / SUMMER LINEN EDIT'), TEXT('subtitle', 'Subheading', 'NATURAL FIBERS & BREATHABLE SILHOUETTES'),
    TEXT('cta_label', 'Button text', 'EXPLORE LINEN CAPSULE'), LINK('cta_link', 'Button goes to'),
    ...PRODUCTS(4),
  ],
  product_marquee: [
    TEXT('title', 'Tag text', 'Picked for you'), MEDIA('image', 'Background photo'),
    TEXT('see_all_label', 'Link text', 'Shop all'), LINK('see_all_link', 'Link goes to'),
    ...PRODUCTS(),
  ],
  drop_countdown: [
    TEXT('eyebrow', 'Small label', 'Look 07 · Archive 01'), TEXT('title', 'Heading', 'Shop the look'),
    MEDIA('image', 'Look photo'),
    TEXT('cta_label', 'Button text', 'Full look'), LINK('cta_link', 'Button goes to'),
    TEXT('button_label', 'Product button text', 'Choose size'),
    ...PRODUCTS(4),
    { key: 'spots', label: 'Hotspots on the photo (one per product, in order)', type: 'list', itemLabel: 'Hotspot',
      hint: 'Position in % from the left (x) and from the top (y).',
      itemFields: [{ key: 'x', label: 'From left %', type: 'number' }, { key: 'y', label: 'From top %', type: 'number' }] },
  ],
  split_scroll: [
    TEXT('phrase', 'Moving phrase', 'Wear what matters · New season · '), AREA('caption', 'Caption'),
    TEXT('title', 'Tag text', 'The edit'), TEXT('see_all_label', 'Link text', 'View all'), LINK('see_all_link', 'Link goes to'),
    ...PRODUCTS(8),
  ],
  standing_look: [
    MEDIA('image', 'Model photo'), TEXT('title', 'Column heading', 'Complete the look'),
    TEXT('see_all_label', 'Link text', 'All'), LINK('see_all_link', 'Link goes to'),
    AREA('headline_lines', 'Big headline (one line per row)', 'Built / to be'),
    TEXT('headline_highlight', 'Highlighted last line', 'lived in'),
    TEXT('cta_label', 'Button text', 'Shop the full look'), LINK('cta_link', 'Button goes to'),
    ...PRODUCTS(10),
  ],
  phone_showcase: [
    MEDIA('image', 'Model photo'), TEXT('brand', 'Brand name on the phones', 'Vault 26'),
    TEXT('screen_title', 'Phone screen title', 'Shop all'),
    TEXT('chips', 'Filter chips (comma separated)', 'All pieces, New, Bestsellers, Only here, Pre-order, Sale'),
    TEXT('email', 'Email shown', 'hello@vault26.co.in'), TEXT('phone', 'Phone shown', '+91 99999 99999'),
    TEXT('hours', 'Hours line', 'Made in India · Mon–Sun 11–20'),
    TEXT('cta_label', 'Button text', 'Shop on any screen'), LINK('cta_link', 'Button goes to'),
    ...PRODUCTS(12),
  ],
  polka_bento: [
    TEXT('title', 'Tag text', 'The season board'), TEXT('see_all_label', 'Link text', 'Shop everything'), LINK('see_all_link', 'Link goes to'),
    MEDIA('campaign_image', 'Campaign tile photo'), TEXT('campaign_title', 'Campaign title', 'Autumn / Winter'),
    TEXT('campaign_cta', 'Campaign link text', 'Shop the campaign'), LINK('campaign_link', 'Campaign tile goes to'),
    TEXT('offer_eyebrow', 'Red tile label', 'Members'), TEXT('offer_text', 'Red tile text', '−15% on first order'), LINK('offer_link', 'Red tile goes to'),
    TEXT('stat_eyebrow', 'Black tile label', 'Since 2026'), TEXT('stat_value', 'Black tile number', '650+'), TEXT('stat_text', 'Black tile text', 'pieces made to outlive the season'),
    MEDIA('lookbook_image', 'Wide tile photo'), TEXT('lookbook_cta', 'Wide tile button', 'Open the lookbook'), LINK('lookbook_link', 'Wide tile goes to'),
    MEDIA('tile_image', 'Small photo tile'), TEXT('tile_label', 'Small photo tile label', 'Outerwear'), LINK('tile_link', 'Small photo tile goes to'),
    TEXT('service_title', 'Outline tile title', 'Delivered in 3–5 days'), TEXT('service_text', 'Outline tile text', 'Free shipping over ₹999 · 7-day returns · COD available'),
    ...PRODUCTS(3),
  ],
};
