import { lazy } from 'react';
import type { FieldDef } from './types';

export const SECTION_COMPONENTS = {
  hero:              lazy(() => import('./sections/HeroSection')),
  category_bar:      lazy(() => import('./sections/CategoryBarSection')),
  campaign_carousel: lazy(() => import('./sections/CampaignCarouselSection')),
  best_sellers:      lazy(() => import('./sections/BestSellersSection')),
  collections:       lazy(() => import('./sections/CollectionsSection')),
  text_reveal:       lazy(() => import('./sections/TextRevealSection')),
  editorial_split:   lazy(() => import('./sections/EditorialSplitSection')),
  bento_grid:        lazy(() => import('./sections/BentoGridSection')),
  new_arrivals:      lazy(() => import('./sections/NewArrivalsSection')),
  category_grid:     lazy(() => import('./sections/CategoryGridSection')),
  marquee:           lazy(() => import('./sections/MarqueeSection')),
  testimonials:      lazy(() => import('./sections/TestimonialsSection')),
  lookbook:          lazy(() => import('./sections/LookbookSection')),
  newsletter:        lazy(() => import('./sections/NewsletterSection')),
  promo_banner:      lazy(() => import('./sections/PromoBannerSection')),
  faq:               lazy(() => import('./sections/FAQSection')),
  linen_collection:  lazy(() => import('./sections/LinenCollectionSection')),
  instagram_reels:   lazy(() => import('./sections/InstagramReelsSection')),
  flagship_stores:   lazy(() => import('./sections/FlagshipStoresSection')),
};

export const SECTION_META: Record<string, { label: string; description: string }> = {
  hero:             { label: 'Hero',             description: 'Full-screen hero with background image and search' },
  category_bar:      { label: 'Category Bar',     description: 'Horizontal clothing category cards bar with thumbnails' },
  campaign_carousel:{ label: 'Campaign Carousel',description: 'Full-width rounded hero campaign banner slider' },
  best_sellers:      { label: 'Best Sellers',     description: 'Curated showcase of top-rated iconic pieces' },
  collections:       { label: 'New Collections',  description: 'Curated seasonal capsule collections grid' },
  text_reveal:      { label: 'Text Reveal',      description: 'Animated large-type reveal words' },
  editorial_split:  { label: 'Editorial Split',  description: 'Two-column: image on one side, text on the other' },
  bento_grid:       { label: 'Bento Grid',       description: 'Magazine-style image grid' },
  new_arrivals:     { label: 'New Arrivals',      description: 'Featured product grid from catalog' },
  category_grid:    { label: 'Category Grid',    description: 'Shop category blocks with hero images' },
  marquee:          { label: 'Marquee',          description: 'Editorial statement section with animated background' },
  testimonials:     { label: 'Testimonials',     description: 'Draggable customer review carousel' },
  lookbook:         { label: 'Lookbook',         description: 'Photo gallery grid' },
  newsletter:       { label: 'Newsletter',       description: 'Email signup / Join the Vault section' },
  promo_banner:     { label: 'Promo Banner',     description: 'Full-width promotional strip' },
  faq:              { label: 'FAQ',              description: 'Expandable frequently asked questions' },
  linen_collection: { label: 'Linen Collection', description: 'Summer European linen capsule showcase' },
  instagram_reels:  { label: 'Instagram Reels',   description: 'Interactive video reels showcase' },
  flagship_stores:  { label: 'Flagship Stores',  description: 'Daily Paper style flagship storefront showcase with giant brand text' },
};

export const SECTION_FIELDS: Record<string, FieldDef[]> = {
  hero: [
    { key: 'heading',           label: 'Main Heading',        type: 'text',     placeholder: 'BEYOND' },
    { key: 'heading_italic',    label: 'Italic Part',         type: 'text',     placeholder: 'TRENDS.' },
    { key: 'eyebrow',           label: 'Eyebrow Label',       type: 'text' },
    { key: 'background_image',  label: 'Background Image URL',type: 'url' },
    { key: 'search_placeholder',label: 'Search Placeholder',  type: 'text' },
    { key: 'search_cta',        label: 'Search Button Text',  type: 'text' },
    { key: 'cta_href',          label: 'Search CTA Link',     type: 'text' },
    { key: 'social_proof_count',label: 'Social Proof Count',  type: 'text',     placeholder: '2K+' },
    { key: 'social_proof_text', label: 'Social Proof Text',   type: 'text' },
  ],
  category_bar: [
    { key: 'categories', label: 'Categories (JSON)', type: 'json', hint: '[{slug, title, image, href}]' },
  ],
  best_sellers: [
    { key: 'eyebrow',      label: 'Eyebrow Label',    type: 'text' },
    { key: 'title',        label: 'Section Title',    type: 'text' },
    { key: 'subtitle',     label: 'Subtitle',         type: 'text' },
    { key: 'cta_label',    label: 'CTA Label',        type: 'text' },
    { key: 'cta_href',     label: 'CTA Link',         type: 'text' },
    { key: 'product_count',label: 'Products to Show', type: 'number' },
  ],
  text_reveal: [
    { key: 'words',           label: 'Words (JSON array)',  type: 'json', hint: '["ATTITUDE","CONFIDENCE"]' },
    { key: 'show_accent_line',label: 'Show Accent Line',   type: 'boolean' },
  ],
  editorial_split: [
    { key: 'image',         label: 'Image URL',              type: 'url' },
    { key: 'accent_number', label: 'Accent Number',          type: 'text',  placeholder: '26' },
    { key: 'heading_lines', label: 'Heading Lines (JSON)',   type: 'json',  hint: '["Redefining","Street Culture"]' },
    { key: 'body',          label: 'Body Text',              type: 'textarea' },
    { key: 'cta_label',     label: 'CTA Label',              type: 'text' },
    { key: 'cta_href',      label: 'CTA Link',               type: 'text' },
  ],
  bento_grid: [
    { key: 'eyebrow',       label: 'Eyebrow',                type: 'text' },
    { key: 'heading',       label: 'Heading',                type: 'text' },
    { key: 'heading_italic',label: 'Heading Italic Part',    type: 'text' },
    { key: 'cta_label',     label: 'CTA Label',              type: 'text' },
    { key: 'cta_href',      label: 'CTA Link',               type: 'text' },
    { key: 'items',         label: 'Grid Items (JSON)',       type: 'json',  hint: '[{title, category, image, href, col_span, row_span}]' },
  ],
  new_arrivals: [
    { key: 'eyebrow',      label: 'Eyebrow',          type: 'text' },
    { key: 'title',        label: 'Section Title',    type: 'text' },
    { key: 'subtitle',     label: 'Subtitle',         type: 'text' },
    { key: 'cta_label',    label: 'CTA Label',        type: 'text' },
    { key: 'cta_href',     label: 'CTA Link',         type: 'text' },
    { key: 'product_count',label: 'Products to Show', type: 'number' },
  ],
  category_grid: [
    { key: 'categories', label: 'Categories (JSON)', type: 'json', hint: '[{slug, title, image, href, watermark, badge?}]' },
  ],
  marquee: [
    { key: 'heading',        label: 'Heading',            type: 'text' },
    { key: 'heading_italic', label: 'Heading Italic Part',type: 'text' },
    { key: 'subtext',        label: 'Subtext',            type: 'text' },
    { key: 'watermark',      label: 'Watermark Character',type: 'text', placeholder: '26' },
  ],
  testimonials: [
    { key: 'heading',        label: 'Heading',            type: 'text' },
    { key: 'heading_italic', label: 'Heading Italic',     type: 'text' },
  ],
  lookbook: [
    { key: 'heading', label: 'Heading',               type: 'text' },
    { key: 'images',  label: 'Image URLs (JSON)',      type: 'json', hint: '["https://...","https://..."]' },
  ],
  newsletter: [
    { key: 'heading_line1', label: 'Heading Line 1',  type: 'text' },
    { key: 'heading_line2', label: 'Heading Line 2',  type: 'text' },
    { key: 'body',          label: 'Body Text',       type: 'textarea' },
    { key: 'placeholder',   label: 'Email Placeholder',type: 'text' },
    { key: 'cta_label',     label: 'CTA Label',       type: 'text' },
  ],
  promo_banner: [
    { key: 'message',   label: 'Message',         type: 'text' },
    { key: 'cta_label', label: 'CTA Label',        type: 'text' },
    { key: 'cta_href',  label: 'CTA Link',         type: 'text' },
    { key: 'bg_color',  label: 'Background Color', type: 'color' },
    { key: 'text_color',label: 'Text Color',       type: 'color' },
  ],
  faq: [
    { key: 'heading',  label: 'Section Heading',         type: 'text' },
    { key: 'category', label: 'Category Filter (empty=all)', type: 'text' },
  ],
};
