import { toast } from 'sonner';

export interface RazorpayOrderResponse {
  order_id: string;
  amount: number;
  currency: string;
  receipt?: string;
  key_id?: string;
  error?: string;
}

export interface RazorpayPaymentSuccessResponse {
  razorpay_payment_id: string;
  razorpay_order_id: string;
  razorpay_signature: string;
}

export interface RazorpayPaymentFailedResponse {
  error: {
    code: string;
    description: string;
    source: string;
    step: string;
    reason: string;
    metadata: {
      order_id: string;
      payment_id: string;
    };
  };
}

export interface RazorpayCheckoutOptions {
  amount: number; // In paise (minimum 100 paise)
  receipt?: string;
  currency?: string;
  name?: string;
  description?: string;
  image?: string;
  prefill?: {
    name?: string;
    email?: string;
    contact?: string;
  };
  notes?: Record<string, string>;
  theme?: {
    color?: string;
  };
  onSuccess?: (response: RazorpayPaymentSuccessResponse) => void | Promise<void>;
  onFailure?: (response: RazorpayPaymentFailedResponse) => void;
  onDismiss?: () => void;
}

/**
 * Ensures the Razorpay checkout script is loaded into the browser document.
 */
export function loadRazorpayScript(): Promise<boolean> {
  return new Promise((resolve) => {
    if ((window as any).Razorpay) {
      return resolve(true);
    }
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.async = true;
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
}

/**
 * Backend call: POST /api/create-order
 * Creates an order on Razorpay servers.
 */
export async function createRazorpayOrder(
  amount: number, // in paise
  receipt?: string,
  currency = 'INR'
): Promise<RazorpayOrderResponse> {
  const res = await fetch('/api/create-order', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ amount, receipt, currency }),
  });

  const data = await res.json();
  if (!res.ok) {
    throw new Error(data.error || 'Failed to create Razorpay order');
  }
  return data;
}

/**
 * Backend call: POST /api/verify-payment
 * Verifies the HMAC-SHA256 signature generated by Razorpay.
 */
export async function verifyRazorpayPayment(
  paymentData: RazorpayPaymentSuccessResponse & { order_id?: string }
): Promise<{ success: boolean; message?: string; error?: string }> {
  const res = await fetch('/api/verify-payment', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(paymentData),
  });

  const data = await res.json();
  if (!res.ok || !data.success) {
    throw new Error(data.error || 'Payment signature verification failed');
  }
  return data;
}

/**
 * Opens the standard Razorpay payment modal with full lifecycle event handling:
 * 1. Calls /api/create-order
 * 2. Initializes Razorpay modal
 * 3. On success, verifies signature via /api/verify-payment
 * 4. Handles payment.failed and modal dismiss
 */
export async function openRazorpayCheckout(
  options: RazorpayCheckoutOptions
): Promise<RazorpayPaymentSuccessResponse> {
  const isLoaded = await loadRazorpayScript();
  if (!isLoaded) {
    const err = new Error('Razorpay SDK failed to load. Please check your internet connection.');
    toast.error(err.message);
    throw err;
  }

  // Ensure minimum amount of 100 paise
  const amountInPaise = Math.round(options.amount);
  if (amountInPaise < 100) {
    const err = new Error('Amount must be at least ₹1.00 (100 paise)');
    toast.error(err.message);
    throw err;
  }

  // Step 1: Create Order via Backend
  const orderData = await createRazorpayOrder(
    amountInPaise,
    options.receipt,
    options.currency || 'INR'
  );

  const keyId =
    import.meta.env.VITE_RAZORPAY_KEY_ID ||
    orderData.key_id;

  if (!keyId) {
    const err = new Error('Razorpay Key ID is not configured');
    toast.error(err.message);
    throw err;
  }

  return new Promise((resolve, reject) => {
    const rzpOptions = {
      key: keyId,
      amount: orderData.amount,
      currency: orderData.currency || 'INR',
      name: options.name || 'Vault 26',
      description: options.description || `Order #${options.receipt || orderData.order_id}`,
      image: options.image || 'https://res.cloudinary.com/dsqeawg67/image/upload/w_180,h_180,c_fill,f_png/v1782059314/v26_utnu5l.png',
      order_id: orderData.order_id,
      prefill: options.prefill || {},
      notes: options.notes || {},
      theme: options.theme || { color: '#B11226' },
      handler: async (response: RazorpayPaymentSuccessResponse) => {
        try {
          // Step 3: Verify Payment Signature via Backend
          await verifyRazorpayPayment({
            ...response,
            order_id: options.receipt,
          });

          if (options.onSuccess) {
            await options.onSuccess(response);
          }
          resolve(response);
        } catch (verifyError: any) {
          toast.error(verifyError.message || 'Payment signature verification failed');
          reject(verifyError);
        }
      },
      modal: {
        ondismiss: () => {
          if (options.onDismiss) {
            options.onDismiss();
          }
          reject(new Error('Payment window was closed by user.'));
        },
      },
    };

    const rzpInstance = new (window as any).Razorpay(rzpOptions);

    // Handle payment failures
    rzpInstance.on('payment.failed', (response: RazorpayPaymentFailedResponse) => {
      console.error('Razorpay payment failed:', response.error);
      toast.error(`Payment failed: ${response.error.description || 'Transaction declined'}`);
      if (options.onFailure) {
        options.onFailure(response);
      }
      reject(new Error(response.error.description || 'Payment failed'));
    });

    rzpInstance.open();
  });
}
